# duti を使ってファイルのデフォルトアプリケーションを設定するための定義ファイルです。
# setup_duti.sh スクリプトから読み込まれます。

# テキストファイル
- bundle_id: com.todesktop.230313mzl4w4u92 # Cursor
  extensions:
    - .txt
    - .md
    - .csv
    - .tsv
    - .ini
    - .json
    - .xml
    - .yaml
    - .yml
    - .css
    - .js
    - .php
    - .py
    - .rb
    - .swift
    - .go
    - .c
    - .cpp
    - .h
    - .sh
    - .bat
    - .ps1
    - .sql
    - .gitignore
    - .editorconfig

- bundle_id: com.apple.TextEdit
  extensions:
    - .rtf

- bundle_id: com.apple.Console
  extensions:
    - .log

# Microsoft Office ファイル
- bundle_id: com.microsoft.Word
  extensions:
    - .doc
    - .docx
- bundle_id: com.microsoft.Excel
  extensions:
    - .xls
    - .xlsx
- bundle_id: com.microsoft.Powerpoint
  extensions:
    - .ppt
    - .pptx

# ドキュメントファイル
- bundle_id: com.apple.Preview
  extensions:
    - .pdf
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
    - .tiff
    - .svg
    - .heic
- bundle_id: com.apple.iBooksX
  extensions:
    - .epub

# メディアファイル
- bundle_id: com.colliderli.iina
  extensions:
    - .mp4
    - .mov
    - .avi
    - .mkv
    - .wmv
    - .mp3
    - .wav
    - .aac
    - .flac
    - .ogg
    - .m4a

# アーカイブファイル
- bundle_id: com.apple.archiveutility
  extensions:
    - .zip
    - .tar
    - .gz
    - .bz2
    - .xz
    - .7z

# ディスクイメージ
- bundle_id: com.apple.DiskImageMounter
  extensions:
    - .dmg
    - .iso

# インストーラー
- bundle_id: com.apple.installer
  extensions:
    - .pkg

# URLリンクファイル
- bundle_id: company.thebrowser.Browser
  extensions:
    - .webloc
    - .url
    - .webp
