# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!
  # But matches can also be dynamic:
  # And much more! For more information, visit the docs: https://espanso.org/docs/

  - trigger: '\today'
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%Y%m%d"

  - trigger: phd
    replace: Ph.D.

  - trigger: '\tbd'
    replace: To be discussed

  - trigger: '\tbc'
    replace: To be confirmed

  # Color Sceme

  - trigger: '\clr'
    replace: 06883F
    label: JCR Pharma

  - trigger: '\clr'
    replace: 003F73
    label: "[Koopa]小野薬品工業/Ono"

  - trigger: '\clr'
    replace: 67C688
    label: "[Peach]ファーマフーズ/Pharam Foods/PFI"

  - trigger: '\clr'
    replace: 4BB234
    label: "[Koratta]Axcelead Drug Discovery Partners/ADDP"

  - trigger: '\clr'
    replace: C43D33
    label: "[Donkey]YUMAB"

  - trigger: '\clr'
    replace: EE1337
    label: "[FF]Fuji Film"

  - trigger: '\clr'
    replace: FF0000
    label: "[Pikachu]帝人ファーマ/Teijin/TPM"

  - trigger: '\clr'
    replace: 005BAA
    label: "[Caterpie]第一三共/Daiichi Sankyo/DS"

  - trigger: '\clr'
    replace: CC0200
    label: "[Hitokage]日立製作所/Hitachi"

  - trigger: '\clr'
    replace: 01E47D
    label: "[Kuribo]Boehringer Ingelheim"

  - trigger: '\clr'
    replace: 7B00E6
    label: "[Sand]Sanofi"

  # Shell Commands

  - trigger: '\git'
    replace: 'git add . && git commit -m "$|$" && git push'

  # テキスト補完

  - triggers: [Mesot, mesot]
    replace: Mesothelin

  - triggers: [Boeh, boeh]
    replace: Boehringer Ingelheim

  # Laten

  - trigger: etc
    replace: "etc. "

  - trigger: e.g
    replace: "e.g., "

  # Laten Italic

  - trigger: de novo
    markdown: "*de novo*"

  - trigger: De novo
    markdown: "*De novo*"

  - trigger: in vivo
    markdown: "*in vivo*"

  - trigger: in vitro
    markdown: "*in vitro*"

  - trigger: in silico
    markdown: "*in silico*"

  - trigger: etal
    markdown: "*et al.*"

  # Correct spelling

  - trigger: modarity
    replace: modality

  - trigger: Temas
    replace: Teams

  - trigger: experiemental
    replace: experimental

  - trigger: quikc
    replace: quick

  # 記号

  - trigger: '\command'
    replace: ⌘

  - trigger: '\option'
    replace: ⌥

  - trigger: '\control'
    replace: "^"

  - trigger: '\dia'
    replace: ✦

  - trigger: '\sft'
    replace: ⇧

  - trigger: '\shift'
    replace: ⇧

  - trigger: '\ctr'
    replace: "^"

  - trigger: '\cmd'
    replace: ⌘

  - trigger: '\opt'
    replace: ⌥

  - trigger: '\hyper'
    replace: ✦

  # 曜日

  - triggers: ['\getu', '\mon']
    replace: （月）

  - triggers: ['\ka', '\tue']
    replace: （火）

  - triggers: ['\sui', '\wed']
    replace: （水）

  - triggers: ['\moku', '\thu']
    replace: （木）

  - triggers: ['\kin', '\fri']
    replace: （金）

  - triggers: ['\do', '\sat']
    replace: （土）

  - triggers: ['\niti', '\nichi', '\sun']
    replace: （日）

  # Prompts

  - triggers: ['\dr', '\deepr']
    replace: "余計な一般論はいっさい不要です。指示した調査内容に限定し、詳細かつ簡潔なアウトプットをしてください。"
